/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PersonalToolsRouteImport } from './routes/personal-tools'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as StylesyncRouteImport } from './routes/stylesync'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as EventsTokenRouteImport } from './routes/events.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalToolsRoute = PersonalToolsRouteImport.update({
  id: '/personal-tools',
  path: '/personal-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesyncRoute = StylesyncRouteImport.update({
  id: '/stylesync',
  path: '/stylesync',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTokenRoute = EventsTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => EventsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/export': typeof ExportRoute
  '/intelligence': typeof IntelligenceRoute
  '/legal': typeof LegalRoute
  '/notes': typeof NotesRoute
  '/personal-tools': typeof PersonalToolsRoute
  '/pricing': typeof PricingRoute
  '/space': typeof SpaceRoute
  '/sports': typeof SportsRoute
  '/stylesync': typeof StylesyncRoute
  '/tasks': typeof TasksRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events/$token': typeof EventsTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/export': typeof ExportRoute
  '/intelligence': typeof IntelligenceRoute
  '/legal': typeof LegalRoute
  '/notes': typeof NotesRoute
  '/personal-tools': typeof PersonalToolsRoute
  '/pricing': typeof PricingRoute
  '/space': typeof SpaceRoute
  '/sports': typeof SportsRoute
  '/stylesync': typeof StylesyncRoute
  '/tasks': typeof TasksRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events/$token': typeof EventsTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/calendar': typeof CalendarRoute
  '/categories': typeof CategoriesRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/export': typeof ExportRoute
  '/intelligence': typeof IntelligenceRoute
  '/legal': typeof LegalRoute
  '/notes': typeof NotesRoute
  '/personal-tools': typeof PersonalToolsRoute
  '/pricing': typeof PricingRoute
  '/space': typeof SpaceRoute
  '/sports': typeof SportsRoute
  '/stylesync': typeof StylesyncRoute
  '/tasks': typeof TasksRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events/$token': typeof EventsTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/book'
    | '/business'
    | '/calendar'
    | '/categories'
    | '/discover'
    | '/events'
    | '/export'
    | '/intelligence'
    | '/legal'
    | '/notes'
    | '/personal-tools'
    | '/pricing'
    | '/space'
    | '/sports'
    | '/stylesync'
    | '/tasks'
    | '/appointments/$id'
    | '/businesses/$slug'
    | '/events/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/book'
    | '/business'
    | '/calendar'
    | '/categories'
    | '/discover'
    | '/events'
    | '/export'
    | '/intelligence'
    | '/legal'
    | '/notes'
    | '/personal-tools'
    | '/pricing'
    | '/space'
    | '/sports'
    | '/stylesync'
    | '/tasks'
    | '/appointments/$id'
    | '/businesses/$slug'
    | '/events/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/book'
    | '/business'
    | '/calendar'
    | '/categories'
    | '/discover'
    | '/events'
    | '/export'
    | '/intelligence'
    | '/legal'
    | '/notes'
    | '/personal-tools'
    | '/pricing'
    | '/space'
    | '/sports'
    | '/stylesync'
    | '/tasks'
    | '/appointments/$id'
    | '/businesses/$slug'
    | '/events/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BusinessRoute: typeof BusinessRoute
  CalendarRoute: typeof CalendarRoute
  CategoriesRoute: typeof CategoriesRoute
  DiscoverRoute: typeof DiscoverRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExportRoute: typeof ExportRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LegalRoute: typeof LegalRoute
  NotesRoute: typeof NotesRoute
  PersonalToolsRoute: typeof PersonalToolsRoute
  PricingRoute: typeof PricingRoute
  SpaceRoute: typeof SpaceRoute
  SportsRoute: typeof SportsRoute
  StylesyncRoute: typeof StylesyncRoute
  TasksRoute: typeof TasksRoute
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-tools': {
      id: '/personal-tools'
      path: '/personal-tools'
      fullPath: '/personal-tools'
      preLoaderRoute: typeof PersonalToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylesync': {
      id: '/stylesync'
      path: '/stylesync'
      fullPath: '/stylesync'
      preLoaderRoute: typeof StylesyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$token': {
      id: '/events/$token'
      path: '/$token'
      fullPath: '/events/$token'
      preLoaderRoute: typeof EventsTokenRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsTokenRoute: typeof EventsTokenRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsTokenRoute: EventsTokenRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BusinessRoute: BusinessRoute,
  CalendarRoute: CalendarRoute,
  CategoriesRoute: CategoriesRoute,
  DiscoverRoute: DiscoverRoute,
  EventsRoute: EventsRouteWithChildren,
  ExportRoute: ExportRoute,
  IntelligenceRoute: IntelligenceRoute,
  LegalRoute: LegalRoute,
  NotesRoute: NotesRoute,
  PersonalToolsRoute: PersonalToolsRoute,
  PricingRoute: PricingRoute,
  SpaceRoute: SpaceRoute,
  SportsRoute: SportsRoute,
  StylesyncRoute: StylesyncRoute,
  TasksRoute: TasksRoute,
  AppointmentsIdRoute: AppointmentsIdRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
