// FireVibe schema: edit this file, then use migrate_database.
import { pgTable, text, timestamp, uuid, integer, boolean } from 'drizzle-orm/pg-core'
import { user } from './auth-schema'

export * from './auth-schema'
export * from './storage-schema'

export const businesses = pgTable('businesses', { id: uuid().primaryKey().defaultRandom(), ownerId: text().references(() => user.id, { onDelete: 'cascade' }), name: text().notNull(), slug: text().notNull().unique(), industry: text().notNull(), city: text().notNull(), phone: text(), address: text(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const professionals = pgTable('professionals', { id: uuid().primaryKey().defaultRandom(), businessId: uuid().notNull().references(() => businesses.id), name: text().notNull(), role: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const services = pgTable('services', { id: uuid().primaryKey().defaultRandom(), businessId: uuid().notNull().references(() => businesses.id), name: text().notNull(), durationMinutes: text().notNull(), price: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const availability = pgTable('availability', { id: uuid().primaryKey().defaultRandom(), professionalId: uuid().notNull().references(() => professionals.id), day: text().notNull(), slots: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const customers = pgTable('customers', { id: uuid().primaryKey().defaultRandom(), businessId: uuid().notNull().references(() => businesses.id, { onDelete: 'cascade' }), name: text().notNull(), email: text(), phone: text(), notes: text(), loyaltyPoints: integer().notNull().default(0), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const tasks = pgTable('tasks', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), title: text().notNull(), category: text().notNull().default('Kişisel görevler'), period: text().notNull().default('today'), priority: text().notNull().default('medium'), completed: boolean().notNull().default(false), pinned: boolean().notNull().default(false), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const appointments = pgTable('appointments', { id: uuid().primaryKey().defaultRandom(), businessId: uuid().notNull().references(() => businesses.id), professionalId: uuid().notNull().references(() => professionals.id), serviceId: uuid().notNull().references(() => services.id), customerId: uuid().references(() => customers.id), ownerId: text().references(() => user.id, { onDelete: 'cascade' }), customerName: text().notNull(), customerEmail: text().notNull(), startsAt: timestamp({ withTimezone: true }).notNull(), status: text().notNull().default('confirmed'), cancellationReason: text(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const appointmentMessages = pgTable('appointment_messages', { id: uuid().primaryKey().defaultRandom(), appointmentId: uuid().notNull().references(() => appointments.id, { onDelete: 'cascade' }), authorId: text().references(() => user.id, { onDelete: 'cascade' }), body: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const moderationEvents = pgTable('moderation_events', { id: uuid().primaryKey().defaultRandom(), userId: text().references(() => user.id, { onDelete: 'cascade' }), surface: text().notNull(), action: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })

export const wardrobeItems = pgTable('wardrobe_items', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), name: text().notNull(), category: text().notNull(), color: text().notNull(), season: text().notNull().default('Tümü'), imageKey: text(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const outfitRecommendations = pgTable('outfit_recommendations', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), weather: text().notNull(), occasion: text().notNull(), recommendation: text().notNull(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const calendarReminders = pgTable('calendar_reminders', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), title: text().notNull(), remindAt: timestamp({ withTimezone: true }).notNull(), enabled: boolean().notNull().default(true), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const userInterests = pgTable('user_interests', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), name: text().notNull(), kind: text().notNull().default('hobi'), intensity: text().notNull().default('merak ediyorum'), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const userLocationPreferences = pgTable('user_location_preferences', { id: uuid().primaryKey().defaultRandom(), userId: text().notNull().references(() => user.id, { onDelete: 'cascade' }).unique(), label: text().notNull(), latitude: text(), longitude: text(), radiusKm: integer().notNull().default(30), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })

export const events = pgTable('events', { id: uuid().primaryKey().defaultRandom(), ownerId: text().notNull().references(() => user.id, { onDelete: 'cascade' }), title: text().notNull(), kind: text().notNull().default('Diğer'), description: text(), location: text().notNull(), startsAt: timestamp({ withTimezone: true }).notNull(), shareToken: text().notNull().unique(), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
export const eventParticipants = pgTable('event_participants', { id: uuid().primaryKey().defaultRandom(), eventId: uuid().notNull().references(() => events.id, { onDelete: 'cascade' }), userId: text().references(() => user.id, { onDelete: 'cascade' }), email: text(), displayName: text().notNull(), status: text().notNull().default('pending'), createdAt: timestamp({ withTimezone: true }).notNull().defaultNow() })
