import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { AlertTriangle, ArrowLeft, CheckCircle2, LogOut, ShieldCheck, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { authClient } from '@/lib/auth-client'
import { useI18n, type Lang } from '@/lib/i18n'
import { deleteAccount } from '@/server/account'

export const Route = createFileRoute('/account')({ head: () => ({ meta: [{ title: 'Hesap ayarları — Planmoy' }] }), component: Account })

type AccountCopy = { loading: string; title: string; signInLead: string; signIn: string; back: string; eyebrow: string; heading: string; lead: string; signOutTitle: string; signOutLead: string; signOut: string; deleteTitle: string; deleteLead: string; confirm: string; delete: string; deleting: string; safe: string; error: string }
const copy: Record<Lang, AccountCopy> = {
  tr: { loading:'Hesap bilgileri yükleniyor…', title:'Hesap ayarları', signInLead:'Bu alanı görmek için giriş yapmalısın.', signIn:'Giriş yap', back:'Akışıma dön', eyebrow:'Güvenlik ve kontrol', heading:'Hesabın senin.', lead:'Verilerini ve çalışma alanını buradan yönet.', signOutTitle:'Oturumu kapat', signOutLead:'Bu cihazdaki oturumunu güvenli şekilde sonlandır.', signOut:'Çıkış yap', deleteTitle:'Hesabı ve verileri sil', deleteLead:'İşletme, randevu, görev ve kişisel kayıtların kalıcı olarak silinir. Bu işlem geri alınamaz.', confirm:'Onay için SİL yaz', delete:'Hesabı sil', deleting:'Siliniyor…', safe:'Ödeme veya kart bilgisi tutulmaz.', error:'Hesap silinemedi. Lütfen tekrar deneyin.' },
  en: { loading:'Loading account details…', title:'Account settings', signInLead:'Sign in to view this area.', signIn:'Sign in', back:'Back to my flow', eyebrow:'Security and control', heading:'Your account, your control.', lead:'Manage your data and workspace here.', signOutTitle:'Sign out', signOutLead:'Safely end your session on this device.', signOut:'Sign out', deleteTitle:'Delete account and data', deleteLead:'Your business, appointments, tasks and personal records will be permanently deleted. This cannot be undone.', confirm:'Type DELETE to confirm', delete:'Delete account', deleting:'Deleting…', safe:'No payment or card details are stored.', error:'We could not delete your account. Please try again.' },
  de: { loading:'Kontodaten werden geladen…', title:'Kontoeinstellungen', signInLead:'Melde dich an, um diesen Bereich zu sehen.', signIn:'Anmelden', back:'Zurück zu meinem Ablauf', eyebrow:'Sicherheit und Kontrolle', heading:'Dein Konto. Deine Kontrolle.', lead:'Verwalte hier deine Daten und deinen Arbeitsbereich.', signOutTitle:'Abmelden', signOutLead:'Beende deine Sitzung auf diesem Gerät sicher.', signOut:'Abmelden', deleteTitle:'Konto und Daten löschen', deleteLead:'Dein Unternehmen, Termine, Aufgaben und persönlichen Einträge werden dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.', confirm:'Zur Bestätigung LÖSCHEN eingeben', delete:'Konto löschen', deleting:'Wird gelöscht…', safe:'Es werden keine Zahlungs- oder Kartendaten gespeichert.', error:'Das Konto konnte nicht gelöscht werden. Bitte versuche es erneut.' },
  fr: { loading:'Chargement des informations du compte…', title:'Paramètres du compte', signInLead:'Connectez-vous pour voir cet espace.', signIn:'Se connecter', back:'Retour à mon flux', eyebrow:'Sécurité et contrôle', heading:'Votre compte, votre contrôle.', lead:'Gérez vos données et votre espace de travail ici.', signOutTitle:'Se déconnecter', signOutLead:'Fermez votre session en toute sécurité sur cet appareil.', signOut:'Se déconnecter', deleteTitle:'Supprimer le compte et les données', deleteLead:'Votre entreprise, vos rendez-vous, tâches et données personnelles seront supprimés définitivement. Cette action est irréversible.', confirm:'Écrivez SUPPRIMER pour confirmer', delete:'Supprimer le compte', deleting:'Suppression…', safe:'Aucune donnée de paiement ou de carte n’est conservée.', error:'Impossible de supprimer le compte. Réessayez.' },
  es: { loading:'Cargando los datos de la cuenta…', title:'Ajustes de la cuenta', signInLead:'Inicia sesión para ver esta área.', signIn:'Iniciar sesión', back:'Volver a mi flujo', eyebrow:'Seguridad y control', heading:'Tu cuenta, tu control.', lead:'Gestiona aquí tus datos y tu espacio de trabajo.', signOutTitle:'Cerrar sesión', signOutLead:'Cierra tu sesión de forma segura en este dispositivo.', signOut:'Cerrar sesión', deleteTitle:'Eliminar cuenta y datos', deleteLead:'Tu negocio, citas, tareas y registros personales se eliminarán permanentemente. Esta acción no se puede deshacer.', confirm:'Escribe ELIMINAR para confirmar', delete:'Eliminar cuenta', deleting:'Eliminando…', safe:'No se guardan datos de pago ni de tarjeta.', error:'No se pudo eliminar la cuenta. Inténtalo de nuevo.' },
  ar: { loading:'جارٍ تحميل معلومات الحساب…', title:'إعدادات الحساب', signInLead:'سجّل الدخول لرؤية هذه المنطقة.', signIn:'تسجيل الدخول', back:'العودة إلى مساري', eyebrow:'الأمان والتحكم', heading:'حسابك، وتحكمك.', lead:'أدر بياناتك ومساحة عملك من هنا.', signOutTitle:'تسجيل الخروج', signOutLead:'أنهِ جلستك بأمان على هذا الجهاز.', signOut:'تسجيل الخروج', deleteTitle:'حذف الحساب والبيانات', deleteLead:'سيتم حذف نشاطك ومواعيدك ومهامك وسجلاتك الشخصية نهائياً. لا يمكن التراجع عن ذلك.', confirm:'اكتب حذف للتأكيد', delete:'حذف الحساب', deleting:'جارٍ الحذف…', safe:'لا يتم حفظ بيانات الدفع أو البطاقة.', error:'تعذر حذف الحساب. حاول مرة أخرى.' },
  ru: { loading:'Загрузка данных аккаунта…', title:'Настройки аккаунта', signInLead:'Войдите, чтобы увидеть этот раздел.', signIn:'Войти', back:'Вернуться к моему потоку', eyebrow:'Безопасность и контроль', heading:'Ваш аккаунт — под вашим контролем.', lead:'Управляйте здесь своими данными и рабочим пространством.', signOutTitle:'Выйти из аккаунта', signOutLead:'Безопасно завершите сеанс на этом устройстве.', signOut:'Выйти', deleteTitle:'Удалить аккаунт и данные', deleteLead:'Ваш бизнес, встречи, задачи и личные записи будут удалены навсегда. Это действие нельзя отменить.', confirm:'Введите УДАЛИТЬ для подтверждения', delete:'Удалить аккаунт', deleting:'Удаление…', safe:'Данные об оплате и картах не хранятся.', error:'Не удалось удалить аккаунт. Попробуйте ещё раз.' },
  zh: { loading:'正在加载账户信息…', title:'账户设置', signInLead:'登录后才能查看此区域。', signIn:'登录', back:'返回我的流程', eyebrow:'安全与控制', heading:'你的账户，由你掌控。', lead:'在这里管理你的数据和工作区。', signOutTitle:'退出登录', signOutLead:'安全地结束此设备上的登录状态。', signOut:'退出登录', deleteTitle:'删除账户和数据', deleteLead:'你的企业、预约、任务和个人记录将被永久删除，且无法恢复。', confirm:'输入删除以确认', delete:'删除账户', deleting:'正在删除…', safe:'不会保存支付或银行卡信息。', error:'无法删除账户，请重试。' },
}

function Account() {
  const navigate = useNavigate(); const { lang } = useI18n(); const t = copy[lang]
  const { data: session, isPending } = authClient.useSession()
  const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const deleteConfirmation = ({ tr: 'SİL', en: 'DELETE', de: 'LÖSCHEN', fr: 'SUPPRIMER', es: 'ELIMINAR', ar: 'حذف', ru: 'УДАЛИТЬ', zh: '删除' } as const)[lang]
  async function remove() { setError(''); setBusy(true); try { await deleteAccount({ data: { confirmation: confirm as typeof deleteConfirmation } }); await authClient.signOut(); await navigate({ to: '/' }) } catch (e) { setError(e instanceof Error ? e.message : t.error); setBusy(false) } }
  if (isPending) return <main className="account-page"><p>{t.loading}</p></main>
  if (!session) return <main className="account-page"><section className="account-card account-gate"><ShieldCheck size={24} /><div><h1>{t.title}</h1><p>{t.signInLead}</p></div><Link className="primary-button" to="/auth">{t.signIn}</Link></section></main>
  return <main className="account-page"><div className="account-wrap"><Link to="/" className="back-link"><ArrowLeft size={15} /> {t.back}</Link><p className="eyebrow blue-label">{t.eyebrow}</p><h1>{t.heading}</h1><p className="account-lead">{session.user.email} · {t.lead}</p><section className="account-card"><ShieldCheck size={22} /><div><h2>{t.signOutTitle}</h2><p>{t.signOutLead}</p></div><button className="secondary-button" onClick={async () => { await authClient.signOut(); await navigate({ to: '/' }) }}><LogOut size={15} /> {t.signOut}</button></section><section className="account-card danger-card"><AlertTriangle size={22} /><div><h2>{t.deleteTitle}</h2><p>{t.deleteLead}</p><label>{t.confirm}<input value={confirm} onChange={e => setConfirm(e.target.value)} aria-label={t.confirm} /></label>{error && <p className="form-error" role="alert">{error}</p>}</div><button className="danger-button" disabled={confirm !== deleteConfirmation || busy} onClick={remove}><Trash2 size={15} /> {busy ? t.deleting : t.delete}</button></section><p className="account-safe"><CheckCircle2 size={15} /> {t.safe}</p></div></main>
}
