import { createFileRoute, Link, notFound } from '@tanstack/react-router'
import { ArrowLeft, CheckCircle2, MessageCircle, Send, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { authClient } from '@/lib/auth-client'
import { getAppointmentDetail, sendAppointmentMessage, updateAppointmentStatus } from '@/server/appointment-actions'
import { findBlockedTerm, moderationMessage } from '@/lib/content-moderation'

export const Route = createFileRoute('/appointments/$id')({ loader: ({ params }) => { if (!params.id) throw notFound(); return { id: params.id } }, component: Appointment })
type Detail = { appointment: { id: string; customerName: string; customerEmail: string; startsAt: Date | string; status: string; cancellationReason: string | null }; messages: { id: string; body: string; createdAt: Date | string }[] }
function Appointment() {
  const { id } = Route.useLoaderData(); const { data: session, isPending } = authClient.useSession(); const [detail, setDetail] = useState<Detail | null>(null); const [body, setBody] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { if (!isPending && session) getAppointmentDetail({ data: { id } }).then(setDetail).catch(() => setError('Bu randevu bulunamadı veya erişim iznin yok.')) }, [id, isPending, session])
  async function status(next: 'confirmed' | 'cancelled' | 'completed') { setBusy(true); setError(''); try { await updateAppointmentStatus({ data: { id, status: next, reason: next === 'cancelled' ? 'İşletme tarafından iptal edildi.' : undefined } }); setDetail(v => v ? { ...v, appointment: { ...v.appointment, status: next } } : v); setNotice(next === 'cancelled' ? 'Randevu iptal edildi.' : 'Randevu durumu güncellendi.') } catch { setError('Randevu durumu güncellenemedi.') } finally { setBusy(false) } }
  async function send(e: React.FormEvent) { e.preventDefault(); if (!body.trim()) return; if (findBlockedTerm(body)) { setError(moderationMessage); return } setBusy(true); setError(''); try { const result = await sendAppointmentMessage({ data: { appointmentId: id, body } }); if (result.message) setDetail(v => v ? { ...v, messages: [...v.messages, result.message!] } : v); setBody(''); setNotice('Mesaj gönderildi.') } catch { setError('Mesaj gönderilemedi. Lütfen tekrar dene.') } finally { setBusy(false) } }
  if (isPending) return <main className="min-h-screen grid place-items-center bg-background text-sm text-muted-foreground">Randevu hazırlanıyor…</main>
  if (!session) return <main className="min-h-screen grid place-items-center bg-background px-6 text-center"><div><MessageCircle className="mx-auto text-accent" /><h1 className="mt-4 text-3xl font-extrabold">Randevu detayına giriş yap.</h1><p className="mt-3 text-sm text-muted-foreground">Bu bilgi yalnızca hesabına bağlı çalışma alanında görünür.</p><Link to="/auth" className="mt-6 inline-flex rounded-lg bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Giriş yap</Link></div></main>
  return <main className="appointment-detail"><div className="appointment-detail-wrap"><Link to="/" className="brand detail-brand">plan<span>moy</span><i /></Link><Link to="/" className="back-link"><ArrowLeft size={14} /> Genel bakış</Link>{error && <div className="form-error" role="alert">{error}</div>}{detail && <><section className="appointment-card"><div><p className="eyebrow blue-label">RANDEVU DETAYI</p><h1>{detail.appointment.customerName}</h1><p className="appointment-meta">{new Date(detail.appointment.startsAt).toLocaleString('tr-TR')} · {detail.appointment.customerEmail}</p></div><span className={`appointment-status ${detail.appointment.status}`}>{detail.appointment.status === 'confirmed' ? 'Onaylı' : detail.appointment.status === 'pending' ? 'Beklemede' : detail.appointment.status === 'completed' ? 'Tamamlandı' : 'İptal edildi'}</span></section><section className="appointment-actions"><button disabled={busy || detail.appointment.status === 'confirmed'} onClick={() => status('confirmed')}><CheckCircle2 size={16} /> Onayla</button><button disabled={busy || detail.appointment.status === 'completed'} onClick={() => status('completed')}><CheckCircle2 size={16} /> Tamamlandı</button><button className="cancel" disabled={busy || detail.appointment.status === 'cancelled'} onClick={() => status('cancelled')}><XCircle size={16} /> İptal et</button></section><section className="message-panel"><div><p className="eyebrow blue-label">GÜVENLİ MESAJLAR</p><h2>Randevu hakkında iletişim</h2><p className="muted-copy">Mesajlar hesabına bağlıdır. Hakaret, tehdit veya uygunsuz içerik gönderilemez.</p></div><div className="message-list">{detail.messages.length ? detail.messages.map(message => <div className="message-bubble" key={message.id}><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString('tr-TR')}</small></div>) : <div className="message-empty"><MessageCircle size={20} /><span>Henüz mesaj yok. İlk mesajı saygılı ve net yaz.</span></div>}</div><form className="message-form" onSubmit={send}><label htmlFor="appointment-message">Mesajın</label><textarea id="appointment-message" value={body} onChange={e => setBody(e.target.value)} maxLength={1000} placeholder="Randevu saatini veya ihtiyacını yaz…" /><button disabled={busy || !body.trim()} className="primary-button"><Send size={15} /> Gönder</button></form>{notice && <p className="appointment-notice" role="status">{notice}</p>}</section></>}</div></main>
}
