import { createFileRoute, Link, Navigate, useParams } from '@tanstack/react-router'
import { CalendarDays, Check, MapPin, Share2, Users, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { authClient } from '@/lib/auth-client'
import { getSharedEvent, respondToEvent } from '@/server/events'

export const Route = createFileRoute('/events/$token')({ head: () => ({ meta: [{ title: 'Etkinlik daveti — Planmoy' }] }), component: SharedEvent })
function SharedEvent() {
  const { token } = useParams({ from: '/events/$token' }); const { data: session } = authClient.useSession(); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { getSharedEvent({ data: { token } }).then(setData).catch(() => setData({ ok:false, message:'Etkinlik yüklenemedi.' })) }, [token])
  async function respond(status: 'going' | 'not_going') { setLoading(true); try { const result = await respondToEvent({ data: { token, status } }); setMessage(result.ok ? 'Yanıtın kaydedildi.' : result.message); if (result.ok) setData(await getSharedEvent({ data: { token } })) } catch { setMessage('Yanıt için Planmoy hesabınla giriş yapmalısın.') } finally { setLoading(false) } }
  if (!data) return <div className="shared-event-page"><p>Etkinlik hazırlanıyor…</p></div>
  if (!data.ok) return <div className="shared-event-page"><Link to="/" className="brand shared-brand">plan<span>moy</span><i /></Link><div className="shared-missing"><X size={30} /><h1>{data.message}</h1><Link to="/" className="primary-button">Ana sayfaya dön</Link></div></div>
  const event = data.event; const going = data.participants.filter((p: any) => p.status === 'going'); const pending = data.participants.filter((p: any) => p.status === 'pending')
  return <div className="shared-event-page"><header className="shared-header"><Link to="/" className="brand shared-brand">plan<span>moy</span><i /></Link><span>Planmoy Social</span></header><main className="shared-wrap"><section className="shared-hero"><div><span className="event-kind">{event.kind}</span><h1>{event.title}</h1><p>{event.description || 'Bu etkinliğin tüm detayları burada. Kimlerin geleceğini birlikte takip edin.'}</p></div><div className="shared-mark"><Share2 size={28} /><span>YOU ARE<br />INVITED</span></div></section><section className="shared-grid"><article className="shared-detail-card"><p><CalendarDays size={18} /><span><small>Tarih ve saat</small><b>{new Date(event.startsAt).toLocaleString('tr-TR', { dateStyle:'full', timeStyle:'short' })}</b></span></p><p><MapPin size={18} /><span><small>Genel konum</small><b>{event.location}</b></span></p><div className="shared-actions">{session ? <><button disabled={loading} className="primary-button" onClick={() => respond('going')}><Check size={16} /> Geliyorum</button><button disabled={loading} className="secondary-button" onClick={() => respond('not_going')}><X size={16} /> Gelemiyorum</button></> : <Link to="/auth" className="primary-button">Yanıtlamak için giriş yap</Link>}</div>{message && <p className="shared-message" role="status">{message}</p>}</article><article className="shared-attendees"><div className="attendees-head"><div><p className="eyebrow blue-label">KATILIM DURUMU</p><h2>Kimler geliyor?</h2></div><span><Users size={14} /> {going.length}</span></div><div className="attendee-list">{going.map((p: any) => <div className="attendee" key={p.displayName}><span className="attendee-avatar">{p.displayName.slice(0,2).toUpperCase()}</span><b>{p.displayName}</b><em>Geliyor</em></div>)}{pending.map((p: any) => <div className="attendee pending" key={p.displayName}><span className="attendee-avatar">?</span><b>{p.displayName}</b><em>Yanıt bekliyor</em></div>)}{!going.length && !pending.length && <p className="empty-attendees">Henüz katılımcı yok.</p>}</div></article></section></main></div>
}
