import { createFileRoute, Link, Navigate } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import {
  ArrowUpRight, CalendarDays, Check, ChevronRight, Compass, FileText, HeartPulse,
  LayoutDashboard, ListChecks, MessageCircle, Plus, Scissors, Settings2, Sparkles,
  Users, WandSparkles, Clock3, Target, StickyNote, Dumbbell,
} from 'lucide-react'
import { getDynamicIconSet, getFlowSuggestion } from '@/server/vibe'
import { getPersonalDashboard } from '@/server/workspace'
import { authClient } from '@/lib/auth-client'
import { useI18n } from '@/lib/i18n'

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Planmoy — Kişisel ve işletme akışı' },
    { name: 'description', content: 'Kişisel planlarını veya işletme randevularını tek bir akışta yönet.' },
  ] }),
  component: Home,
})

type Mode = 'personal' | 'business'
type Lang = 'tr' | 'en' | 'de' | 'fr' | 'es' | 'ar' | 'ru' | 'zh'
type HomeCopy = { personal: string; business: string; personalSub: string; businessSub: string; enter: string; choose: string; language: string; personalTitle: string; businessTitle: string; personalIntro: string; businessIntro: string; personalAction: string; businessAction: string; footer: string; personalFlow: string; businessFlow: string; focusLabel: string; focusText: string; planToday: string }
const copy: Record<Lang, HomeCopy> = {
  tr: { personal: 'Kişisel alan', business: 'İşletme alanı', personalSub: 'Takvimini, görevlerini ve günlük akışını yönet.', businessSub: 'Randevularını, ekibini ve müşteri akışını yönet.', enter: 'Devam et', choose: 'Nasıl kullanacaksın?', language: 'Dil', personalTitle: 'Günün akışı,\nsenin ritminde.', businessTitle: 'İşletmen için\ndaha net bir akış.', personalIntro: 'Randevular, görevler, stil ve keşif önerileri tek bir sakin çalışma alanında.', businessIntro: 'Takvim, hizmetler, ekip ve danışan deneyimi için ihtiyacın olan sade panel.', personalAction: 'Kişisel alana geç', businessAction: 'İşletme paneline geç', footer: 'Kişisel hayat ve işletme akışı, tek noktada.', personalFlow: 'KİŞİSEL AKIŞ', businessFlow: 'İŞLETME AKIŞI', focusLabel: 'BUGÜNÜN ODAĞI', focusText: 'Önce en önemli adımı seç, kalanını Planmoy senin için sakinleştirsin.', planToday: 'Bugünü planla' },
  en: { personal: 'Personal space', business: 'Business space', personalSub: 'Manage your calendar, tasks and daily flow.', businessSub: 'Manage appointments, team and customer flow.', enter: 'Continue', choose: 'How will you use it?', language: 'Language', personalTitle: 'Your day,\nin your rhythm.', businessTitle: 'A clearer flow\nfor your business.', personalIntro: 'Appointments, tasks, style and discovery in one calm workspace.', businessIntro: 'A focused panel for calendars, services, teams and clients.', personalAction: 'Enter personal space', businessAction: 'Enter business panel', footer: 'One clear flow for life and business.', personalFlow: 'PERSONAL FLOW', businessFlow: 'BUSINESS FLOW', focusLabel: 'TODAY’S FOCUS', focusText: 'Choose the most important step first; Planmoy will simplify the rest.', planToday: 'Plan today' },
  de: { personal: 'Persönlicher Bereich', business: 'Unternehmensbereich', personalSub: 'Kalender, Aufgaben und Tagesablauf verwalten.', businessSub: 'Termine, Team und Kundenablauf verwalten.', enter: 'Weiter', choose: 'Wie möchtest du es nutzen?', language: 'Sprache', personalTitle: 'Dein Tag,\nin deinem Rhythmus.', businessTitle: 'Ein klarerer Ablauf\nfür dein Unternehmen.', personalIntro: 'Termine, Aufgaben, Stil und Entdeckungen in einem ruhigen Arbeitsbereich.', businessIntro: 'Ein fokussiertes Panel für Kalender, Leistungen, Teams und Kunden.', personalAction: 'Persönlichen Bereich öffnen', businessAction: 'Unternehmensbereich öffnen', footer: 'Ein klarer Ablauf für Leben und Unternehmen.', personalFlow: 'PERSÖNLICHER ABLAUF', businessFlow: 'GESCHÄFTSABLAUF', focusLabel: 'HEUTIGER FOKUS', focusText: 'Wähle zuerst den wichtigsten Schritt; Planmoy macht den Rest leichter.', planToday: 'Tag planen' },
  fr: { personal: 'Espace personnel', business: 'Espace entreprise', personalSub: 'Gérez votre agenda, vos tâches et votre rythme.', businessSub: 'Gérez vos rendez-vous, votre équipe et vos clients.', enter: 'Continuer', choose: 'Comment allez-vous l’utiliser ?', language: 'Langue', personalTitle: 'Votre journée,\nà votre rythme.', businessTitle: 'Un flux plus clair\npour votre activité.', personalIntro: 'Rendez-vous, tâches, style et découvertes dans un espace serein.', businessIntro: 'Un espace concentré pour agendas, services, équipes et clients.', personalAction: 'Ouvrir l’espace personnel', businessAction: 'Ouvrir l’espace entreprise', footer: 'Un flux clair pour la vie et votre activité.', personalFlow: 'FLUX PERSONNEL', businessFlow: 'FLUX ENTREPRISE', focusLabel: 'FOCUS DU JOUR', focusText: 'Commencez par l’étape la plus importante ; Planmoy simplifie le reste.', planToday: 'Planifier la journée' },
  es: { personal: 'Espacio personal', business: 'Espacio para negocios', personalSub: 'Gestiona tu calendario, tareas y ritmo diario.', businessSub: 'Gestiona citas, equipo y clientes.', enter: 'Continuar', choose: '¿Cómo lo vas a usar?', language: 'Idioma', personalTitle: 'Tu día,\na tu ritmo.', businessTitle: 'Un flujo más claro\npara tu negocio.', personalIntro: 'Citas, tareas, estilo y descubrimientos en un espacio tranquilo.', businessIntro: 'Un panel claro para calendarios, servicios, equipos y clientes.', personalAction: 'Entrar al espacio personal', businessAction: 'Entrar al panel del negocio', footer: 'Un flujo claro para tu vida y negocio.', personalFlow: 'FLUJO PERSONAL', businessFlow: 'FLUJO DE NEGOCIO', focusLabel: 'FOCO DE HOY', focusText: 'Elige primero el paso más importante; Planmoy simplifica el resto.', planToday: 'Planificar hoy' },
  ar: { personal: 'المساحة الشخصية', business: 'مساحة الأعمال', personalSub: 'أدر تقويمك ومهامك وإيقاع يومك.', businessSub: 'أدر المواعيد والفريق وتدفق العملاء.', enter: 'متابعة', choose: 'كيف ستستخدمه؟', language: 'اللغة', personalTitle: 'يومك،\nوفق إيقاعك.', businessTitle: 'تدفق أوضح\nلعملك.', personalIntro: 'المواعيد والمهام والأناقة والاكتشاف في مساحة هادئة واحدة.', businessIntro: 'لوحة مركزة للتقويم والخدمات والفريق والعملاء.', personalAction: 'الدخول إلى المساحة الشخصية', businessAction: 'الدخول إلى لوحة الأعمال', footer: 'تدفق واضح للحياة والعمل.', personalFlow: 'المسار الشخصي', businessFlow: 'مسار الأعمال', focusLabel: 'تركيز اليوم', focusText: 'اختر الخطوة الأهم أولاً؛ وسيبسّط Planmoy بقية يومك.', planToday: 'خطّط ليومك' },
  ru: { personal: 'Личное пространство', business: 'Для бизнеса', personalSub: 'Управляйте календарём, задачами и ритмом дня.', businessSub: 'Управляйте встречами, командой и клиентами.', enter: 'Продолжить', choose: 'Как вы будете использовать Planmoy?', language: 'Язык', personalTitle: 'Ваш день —\nв вашем ритме.', businessTitle: 'Более ясный поток\nдля вашего бизнеса.', personalIntro: 'Встречи, задачи, стиль и открытия в одном спокойном рабочем пространстве.', businessIntro: 'Понятная панель для календаря, услуг, команды и клиентов.', personalAction: 'Открыть личное пространство', businessAction: 'Открыть панель бизнеса', footer: 'Один ясный поток для жизни и бизнеса.', personalFlow: 'ЛИЧНЫЙ ПОТОК', businessFlow: 'ПОТОК БИЗНЕСА', focusLabel: 'ФОКУС ДНЯ', focusText: 'Сначала выберите главный шаг — Planmoy упростит остальное.', planToday: 'Планировать день' },
  zh: { personal: '个人空间', business: '企业空间', personalSub: '管理日历、任务和每日安排。', businessSub: '管理预约、团队和客户流程。', enter: '继续', choose: '你将如何使用 Planmoy？', language: '语言', personalTitle: '掌控每一天，\n按自己的节奏。', businessTitle: '让你的业务\n流程更清晰。', personalIntro: '预约、任务、风格与探索建议，集中在一个平静的工作空间中。', businessIntro: '为日历、服务、团队和客户打造的清晰管理面板。', personalAction: '进入个人空间', businessAction: '进入企业面板', footer: '让生活与业务拥有清晰的节奏。', personalFlow: '个人流程', businessFlow: '企业流程', focusLabel: '今日重点', focusText: '先选择最重要的一步，Planmoy 会让其余安排更简单。', planToday: '规划今天' },
}

const tasks: Record<Lang, string[]> = {
  tr: ['Doktor kontrolü için belge hazırla', 'Perşembe dersini planla', 'Yeni saç modeli için ilham kaydet'], en: ['Prepare documents for the doctor visit', 'Plan Thursday’s lesson', 'Save inspiration for a new haircut'], de: ['Unterlagen für den Arzttermin vorbereiten', 'Donnerstagskurs planen', 'Inspiration für eine neue Frisur speichern'], fr: ['Préparer les documents du rendez-vous médical', 'Planifier le cours de jeudi', 'Enregistrer une idée de nouvelle coupe'], es: ['Preparar documentos para la cita médica', 'Planificar la clase del jueves', 'Guardar inspiración para un nuevo peinado'], ar: ['جهّز مستندات موعد الطبيب', 'خطط لدرس الخميس', 'احفظ إلهاماً لتسريحة جديدة'], ru: ['Подготовить документы к приёму врача', 'Запланировать занятие в четверг', 'Сохранить идею новой стрижки'], zh: ['准备就医所需文件', '安排周四课程', '保存新发型灵感'],
}
const localized: Record<Lang, Partial<Record<string, string[] | string>>> = {
  tr: { nav: ['Genel bakış', 'Zaman akışı', 'Yapılacaklar', 'StyleSync', 'Keşfet', 'Hobi ve hedefler', 'Boş Alan', 'Yapay zeka', 'Kişisel araçlar'], status: ['Bugünün görevleri', 'Yaklaşan randevular', 'Fire puanı', 'Akış dengesi'], weather: 'Parçalı bulutlu · montunu unutma', today: 'BUGÜN', completed: 'tamamlandı', priority: 'Önceliklerini seç', addTask: 'Görev ekle', planToday: 'Bugünü planla', addAppointment: 'Randevu ekle', connectCalendar: 'Takvimine bağla', styleAsk: 'Stil önerisi iste', discoverWith: 'StyleSync ile keşfet', aiAsk: 'Yapay zeka önerisi al', thinking: 'Düşünüyor…', quickStart: 'HIZLI BAŞLANGIÇ', quickTitle: 'Akışına bir adım ekle.', smartFlow: 'AI', balance: 'Bugünün dengesi', thisWeek: 'bu hafta', appText: 'Programın dengeli görünüyor. Randevularının arasında kendine alan bırakmışsın.' },
  en: { nav: ['Overview', 'Time flow', 'Tasks', 'StyleSync', 'Discover', 'Hobbies & goals', 'Empty space', 'Intelligence flow', 'Personal tools'], status: ["Today's tasks", 'Upcoming appointments', 'Fire points', 'Flow balance'], weather: 'Partly cloudy · bring a jacket', today: 'TODAY', completed: 'completed', priority: 'Choose your priorities', addTask: 'Add task', planToday: 'Plan today', addAppointment: 'Add appointment', connectCalendar: 'Connect to calendar', styleAsk: 'Ask for a style idea', discoverWith: 'Explore with StyleSync', aiAsk: 'Get AI advice', thinking: 'Thinking…', quickStart: 'QUICK START', quickTitle: 'Add a step to your flow.', smartFlow: 'AI', balance: "Today's balance", thisWeek: 'this week', businessWorkspace: 'Business workspace for Deniz Flow Studio', openBusiness: 'Open full business panel', todayAppointments: "Today's appointments", first: 'First at 09:30', good: 'Going well', appText: 'Your schedule looks balanced. You have left room for yourself between appointments.' },
  de: { nav: ['Übersicht', 'Zeitablauf', 'Aufgaben', 'StyleSync', 'Entdecken', 'Hobbys & Ziele', 'Freiraum', 'KI', 'Persönliche Werkzeuge'], status: ['Aufgaben heute', 'Kommende Termine', 'Fire-Punkte', 'Flow-Balance'], weather: 'Teilweise bewölkt · Jacke nicht vergessen', today: 'HEUTE', completed: 'erledigt', priority: 'Prioritäten wählen', addTask: 'Aufgabe hinzufügen', planToday: 'Tag planen', addAppointment: 'Termin hinzufügen', connectCalendar: 'Kalender verbinden', styleAsk: 'Stilidee anfragen', discoverWith: 'Mit StyleSync entdecken', aiAsk: 'KI-Vorschlag erhalten', thinking: 'Wird überlegt…', quickStart: 'SCHNELLSTART', quickTitle: 'Füge deinem Flow einen Schritt hinzu.', smartFlow: 'AI', balance: 'Tagesbalance', thisWeek: 'diese Woche', good: 'Läuft gut', appText: 'Dein Zeitplan wirkt ausgeglichen. Zwischen den Terminen bleibt Zeit für dich.' },
  fr: { nav: ['Vue d’ensemble', 'Flux du temps', 'Tâches', 'StyleSync', 'Découvrir', 'Loisirs et objectifs', 'Espace libre', 'Intelligence', 'Outils personnels'], status: ['Tâches du jour', 'Prochains rendez-vous', 'Points Fire', 'Équilibre du flux'], weather: 'Partiellement nuageux · prends une veste', today: 'AUJOURD’HUI', completed: 'terminé', priority: 'Choisis tes priorités', addTask: 'Ajouter une tâche', planToday: 'Planifier la journée', addAppointment: 'Ajouter un rendez-vous', connectCalendar: 'Connecter le calendrier', styleAsk: 'Demander une idée de style', discoverWith: 'Explorer avec StyleSync', aiAsk: 'Obtenir une suggestion IA', thinking: 'Analyse…', quickStart: 'DÉMARRAGE RAPIDE', quickTitle: 'Ajoute une étape à ton flux.', smartFlow: 'AI', balance: 'Équilibre du jour', thisWeek: 'cette semaine', good: 'Tout va bien', appText: 'Ton agenda semble équilibré. Tu as gardé du temps pour toi entre les rendez-vous.' },
  es: { nav: ['Resumen', 'Flujo de tiempo', 'Tareas', 'StyleSync', 'Descubrir', 'Aficiones y metas', 'Espacio libre', 'Inteligencia', 'Herramientas personales'], status: ['Tareas de hoy', 'Próximas citas', 'Puntos Fire', 'Equilibrio del flujo'], weather: 'Parcialmente nublado · lleva una chaqueta', today: 'HOY', completed: 'completado', priority: 'Elige tus prioridades', addTask: 'Añadir tarea', planToday: 'Planificar hoy', addAppointment: 'Añadir cita', connectCalendar: 'Conectar calendario', styleAsk: 'Pedir una idea de estilo', discoverWith: 'Explorar con StyleSync', aiAsk: 'Obtener sugerencia de IA', thinking: 'Pensando…', quickStart: 'INICIO RÁPIDO', quickTitle: 'Añade un paso a tu flujo.', smartFlow: 'AI', balance: 'Equilibrio de hoy', thisWeek: 'esta semana', good: 'Va bien', appText: 'Tu agenda parece equilibrada. Has dejado espacio para ti entre las citas.' },
  ar: { nav: ['نظرة عامة', 'تدفق الوقت', 'المهام', 'StyleSync', 'اكتشف', 'الهوايات والأهداف', 'مساحة فارغة', 'الذكاء الاصطناعي', 'الأدوات الشخصية'], status: ['مهام اليوم', 'المواعيد القادمة', 'نقاط Fire', 'توازن التدفق'], weather: 'غائم جزئياً · لا تنسَ معطفك', today: 'اليوم', completed: 'مكتمل', priority: 'اختر أولوياتك', addTask: 'إضافة مهمة', planToday: 'خطط ليومك', addAppointment: 'إضافة موعد', connectCalendar: 'ربط التقويم', styleAsk: 'اطلب فكرة للأناقة', discoverWith: 'استكشف مع StyleSync', aiAsk: 'احصل على اقتراح من الذكاء الاصطناعي', thinking: 'جارٍ التفكير…', quickStart: 'بداية سريعة', quickTitle: 'أضف خطوة إلى مسارك.', smartFlow: 'AI', balance: 'توازن اليوم', thisWeek: 'هذا الأسبوع', good: 'الأمور جيدة', appText: 'يبدو جدولك متوازناً. لقد تركت وقتاً لنفسك بين المواعيد.' },
  ru: { nav: ['Обзор', 'Расписание', 'Задачи', 'StyleSync', 'Открытия', 'Хобби и цели', 'Свободное пространство', 'Умный поток', 'Личные инструменты'], status: ['Задачи на сегодня', 'Ближайшие встречи', 'Огненные очки', 'Баланс потока'], weather: 'Переменная облачность · не забудьте куртку', today: 'СЕГОДНЯ', completed: 'выполнено', priority: 'Выберите приоритеты', addTask: 'Добавить задачу', planToday: 'Планировать день', addAppointment: 'Добавить встречу', connectCalendar: 'Связать с календарём', styleAsk: 'Запросить идею стиля', discoverWith: 'Открыть в StyleSync', aiAsk: 'Получить совет ИИ', thinking: 'Думаю…', quickStart: 'БЫСТРЫЙ СТАРТ', quickTitle: 'Добавьте шаг в свой поток.', smartFlow: 'Умный поток', balance: 'Баланс дня', thisWeek: 'на этой неделе', businessWorkspace: 'Рабочее пространство Deniz Flow Studio', openBusiness: 'Открыть панель бизнеса', todayAppointments: 'Встречи на сегодня', first: 'Первая в 09:30', good: 'Всё идёт хорошо', appText: 'Ваш график выглядит сбалансированным. Между встречами осталось время для себя.' },
  zh: { nav: ['总览', '时间安排', '待办事项', 'StyleSync', '探索', '兴趣与目标', '留白空间', '智能流程', '个人工具'], status: ['今日任务', '即将到来的预约', 'Fire 积分', '流程平衡'], weather: '多云 · 别忘了带外套', today: '今天', completed: '已完成', priority: '选择你的重点', addTask: '添加任务', planToday: '规划今天', addAppointment: '添加预约', connectCalendar: '连接日历', styleAsk: '获取风格建议', discoverWith: '在 StyleSync 中探索', aiAsk: '获取人工智能建议', thinking: '思考中…', quickStart: '快速开始', quickTitle: '为你的流程添加一步。', smartFlow: '智能流程', balance: '今日平衡', thisWeek: '本周', appText: '你的日程安排很平衡，预约之间留出了属于自己的时间。' },
}
function Home() {
  const [mode, setMode] = useState<Mode>('personal')
  const { lang, setLang } = useI18n()
  const [done, setDone] = useState<number[]>([])
  const [suggestion, setSuggestion] = useState('')
  const [thinking, setThinking] = useState(false)
  const [aiIcons, setAiIcons] = useState<string[]>(['calendar', 'sparkles', 'users'])
  const [dashboard, setDashboard] = useState<{ todayTasks: number; todayAppointments: number; upcomingAppointments: { id: string; customerName: string; startsAt: Date | string; status: string }[] } | null>(null)
  const { data: session, isPending: sessionPending } = authClient.useSession()
  const t = copy[lang] ?? copy.tr
  const iconFor = (name: string, size = 20) => ({ calendar: <CalendarDays size={size} />, heart: <HeartPulse size={size} />, sparkles: <Sparkles size={size} />, users: <Users size={size} />, compass: <Compass size={size} />, list: <ListChecks size={size} />, wand: <WandSparkles size={size} />, clock: <Clock3 size={size} />, target: <Target size={size} />, note: <StickyNote size={size} /> }[name] ?? <Sparkles size={size} />)
  const l = { ...localized.tr, ...(localized[lang] ?? {}) }
  const locale = ({ tr: 'tr-TR', en: 'en-US', de: 'de-DE', fr: 'fr-FR', es: 'es-ES', ar: 'ar-SA', ru: 'ru-RU', zh: 'zh-CN' } as const)[lang] ?? 'tr-TR'
  useEffect(() => {
    if (sessionPending || !session) return
    getDynamicIconSet({ data: { surface: 'Planmoy ana çalışma alanı' } }).then(result => { if (Array.isArray(result?.icons)) setAiIcons(result.icons) }).catch(() => {})
  }, [session, sessionPending])
  useEffect(() => {
    if (!sessionPending && session) getPersonalDashboard().then(setDashboard).catch(() => setDashboard(null))
  }, [session, sessionPending])
  useEffect(() => {
    document.documentElement.lang = lang
    document.title = lang === 'ru' ? 'Planmoy — онлайн-управление встречами' : lang === 'zh' ? 'Planmoy — 在线预约管理' : lang === 'en' ? 'Planmoy — Online appointment management' : lang === 'de' ? 'Planmoy — Online-Terminverwaltung' : lang === 'fr' ? 'Planmoy — gestion des rendez-vous' : lang === 'es' ? 'Planmoy — gestión de citas' : lang === 'ar' ? 'Planmoy — إدارة المواعيد' : 'Planmoy — Online randevu yönetimi'
  }, [lang])
  async function askFlow() { setThinking(true); try { setSuggestion((await getFlowSuggestion({ data: { focus: mode === 'personal' ? 'bugünkü kişisel randevular ve görevler' : 'bugünkü işletme randevuları ve ekip akışı' } })).suggestion) } catch { setSuggestion(mode === 'personal' ? 'Randevularının arasına kısa bir nefes alanı bırakmayı dene.' : 'Yoğun saatlerinden önce ekibine kısa bir hazırlık alanı bırak.') } finally { setThinking(false) } }
  if (!sessionPending && !session) return <Navigate to="/auth" replace />
  return <div className="app-shell overview-blue home-choice">
    <aside className="sidebar"><Link to="/" className="brand">plan<span>moy</span><i /></Link><div className="workspace"><span className="avatar-mark">PM</span><div><strong>Planmoy</strong><small>{mode === 'personal' ? t.personal : t.business}</small></div></div><nav className="side-nav" aria-label="Ana menü"><NavItem active icon={<LayoutDashboard size={17} />} label={String(l['nav']?.[0])} /><NavItem icon={<CalendarDays size={17} />} label={String(l['nav']?.[1])} to="/calendar" /><NavItem icon={<ListChecks size={17} />} label={String(l['nav']?.[2])} to="/tasks" /><NavItem icon={<WandSparkles size={17} />} label={String(l['nav']?.[3])} to="/stylesync" /><NavItem icon={<Compass size={17} />} label={String(l['nav']?.[4])} to="/discover" /><NavItem icon={<Dumbbell size={17} />} label={lang === 'tr' ? 'Spor akışı' : lang === 'ru' ? 'Спортивный поток' : lang === 'en' ? 'Sports flow' : lang === 'de' ? 'Sportablauf' : lang === 'fr' ? 'Flux sportif' : lang === 'es' ? 'Flujo deportivo' : lang === 'ar' ? 'تدفق الرياضة' : '运动流程'} to="/sports" /><NavItem icon={<Users size={17} />} label={lang === 'tr' ? 'Etkinlikler' : lang === 'ru' ? 'События' : lang === 'en' ? 'Events' : lang === 'de' ? 'Veranstaltungen' : lang === 'fr' ? 'Événements' : lang === 'es' ? 'Eventos' : lang === 'ar' ? 'الفعاليات' : '活动'} to="/events" /><NavItem icon={<FileText size={17} />} label={String(l['nav']?.[5])} to="/space" /><NavItem icon={<MessageCircle size={17} />} label={String(l['nav']?.[6])} to="/notes" /><NavItem icon={<Sparkles size={17} />} label={String(l['nav']?.[7])} to="/intelligence" /><NavItem icon={<HeartPulse size={17} />} label={String(l['nav']?.[8])} to="/personal-tools" /></nav><div className="sidebar-bottom"><div className="fire-note"><Sparkles size={16} /><span>Akışını<br /><b>netleştir.</b></span></div><span className="side-caption">Planmoy · cross-platform</span></div></aside>
    <main className="main-canvas"><header className="topbar"><div><p className="eyebrow">Planmoy</p><h1>{t.choose}</h1></div><div className="top-actions"><label className="language-picker"><span>{t.language}</span><select value={lang} onChange={e => setLang(e.target.value as Lang)} aria-label={t.language}>{(['tr','en','de','fr','es','ar','ru','zh'] as Lang[]).map(x => <option key={x} value={x}>{x === 'ru' ? 'РУ' : x === 'zh' ? '中文' : x.toUpperCase()}</option>)}</select></label><span className="platform-note"><i /> Web · Android · iOS</span></div></header>
      <section className="mode-hero"><div><p className="eyebrow blue-label">{mode === 'personal' ? t.personalFlow : t.businessFlow}</p><h2>{(mode === 'personal' ? t.personalTitle : t.businessTitle).split('\n').map((x, i) => <span key={x}>{x}{i === 0 && <br />}</span>)}</h2><p className="intro">{mode === 'personal' ? t.personalIntro : t.businessIntro}</p></div><div className="flow-orb"><span className="orb-ring" /><span className="orb-dot dot-one" /><span className="orb-dot dot-two" /><b>FLOW</b></div></section>
      <section className="mode-switch" aria-label={t.choose}><button className={mode === 'personal' ? 'selected' : ''} onClick={() => setMode('personal')}><span className="mode-icon">{iconFor(aiIcons[0] ?? 'heart')}</span><span><strong>{t.personal}</strong><small>{t.personalSub}</small></span><ChevronRight size={17} /></button><button className={mode === 'business' ? 'selected' : ''} onClick={() => setMode('business')}><span className="mode-icon">{iconFor(aiIcons[1] ?? 'users')}</span><span><strong>{t.business}</strong><small>{t.businessSub}</small></span><ChevronRight size={17} /></button></section>
      {mode === 'personal' ? <PersonalView done={done} setDone={setDone} suggestion={suggestion} thinking={thinking} askFlow={askFlow} t={t} labels={l} dashboard={dashboard} locale={locale} lang={lang} /> : <BusinessView suggestion={suggestion} thinking={thinking} askFlow={askFlow} labels={l} />}
      <footer><span className="brand small">plan<span>moy</span><i /></span><span>{t.footer}</span><Link to="/categories" className="footer-link">Kategori rehberi <ArrowUpRight size={13} /></Link></footer>
    </main>
  </div>
}
function PersonalView({ done, setDone, suggestion, thinking, askFlow, t, labels, dashboard, locale, lang }: { done: number[]; setDone: React.Dispatch<React.SetStateAction<number[]>>; suggestion: string; thinking: boolean; askFlow: () => void; t: typeof copy.tr; labels: Partial<Record<string, string | string[]>>; dashboard: { todayTasks: number; todayAppointments: number; upcomingAppointments: { id: string; customerName: string; startsAt: Date | string; status: string }[] } | null; locale: string; lang: Lang }) {
  const text = (key: string, fallback: string) => String(labels[key] ?? fallback)
  const statusLabels = Array.isArray(labels['status']) ? labels['status'] : ['Görevler', 'Randevular', 'Puanlar', 'Akış dengesi']
  const taskList = tasks[lang] ?? tasks.tr
  const quickActions = [
    { label: text('addTask', 'Görev ekle'), detail: text('planToday', 'Bugünü planla'), icon: <ListChecks size={17} />, to: '/tasks' as const },
    { label: text('addAppointment', 'Randevu ekle'), detail: text('connectCalendar', 'Takvimine bağla'), icon: <CalendarDays size={17} />, to: '/book' as const },
    { label: text('styleAsk', 'Stil önerisi iste'), detail: text('discoverWith', 'StyleSync ile keşfet'), icon: <WandSparkles size={17} />, to: '/stylesync' as const },
  ]
  return <>
    <section className="today-focus-banner"><div><p className="eyebrow blue-label">{t.focusLabel}</p><h2>{dashboard ? `${dashboard.todayTasks} görev ve ${dashboard.todayAppointments} randevu seni bekliyor.` : 'Akışını tek bakışta netleştir.'}</h2><p>{t.focusText}</p></div><Link to="/tasks" className="primary-button">{t.planToday} <ArrowUpRight size={15} /></Link></section><section className="personal-status-row" aria-label={text('balance', 'Günlük durum')}><div className="weather-status"><span className="weather-icon">☼</span><div><b>İstanbul · 19°</b><small>{text('weather', 'Parçalı bulutlu · montunu unutma')}</small></div></div><div className="status-divider" /><div className="day-status"><span className="status-kicker">{text('today', 'BUGÜN')}</span><b>{new Intl.DateTimeFormat(locale, { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</b></div></section>
    <section className="personal-stat-grid"><article className="personal-stat"><span className="stat-icon"><ListChecks size={16} /></span><small>{String(statusLabels[0])}</small><strong>{dashboard ? dashboard.todayTasks : '—'}</strong><em>{done.length ? `${done.length} ${text('completed', 'tamamlandı')}` : text('priority', 'Önceliklerini seç')}</em></article><article className="personal-stat"><span className="stat-icon"><CalendarDays size={16} /></span><small>{String(statusLabels[1])}</small><strong>{dashboard ? dashboard.todayAppointments : '—'}</strong><em>{dashboard?.upcomingAppointments[0] ? `İlki ${new Date(dashboard.upcomingAppointments[0].startsAt).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })}` : 'Yaklaşan randevu yok'}</em></article><article className="personal-stat"><span className="stat-icon"><Sparkles size={16} /></span><small>{String(statusLabels[2])}</small><strong>450</strong><em className="positive">+24 {text('thisWeek', 'bu hafta')}</em></article><article className="personal-stat"><span className="stat-icon"><HeartPulse size={16} /></span><small>{String(statusLabels[3])}</small><strong>72%</strong><em>{text('good', 'İyi gidiyor')}</em></article></section>
    <section className="overview-grid personal-main-grid"><article className="panel schedule-panel"><PanelHeading eyebrow="Zaman akışı" title="Yaklaşanlar" action={<Link to="/calendar">Takvime git <ArrowUpRight size={14} /></Link>} /><div className="appointment-list">{dashboard?.upcomingAppointments.length ? dashboard.upcomingAppointments.slice(0, 3).map(item => <Link className="appointment" key={item.id} to="/appointments/$id" params={{ id: item.id }}><time>{new Date(item.startsAt).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })}</time><span className="event-line blue" /><div><strong>{item.customerName}</strong><p>{item.status === 'confirmed' ? 'Onaylı randevu' : item.status}</p></div><span className="tag">Randevu</span><ChevronRight size={16} className="chevron" /></Link>) : <p className="empty-schedule">Giriş yaptıktan sonra yaklaşan randevuların burada görünür.</p>}</div><Link to="/book" className="add-row"><Plus size={15} /> Yeni randevu ekle</Link></article><article className="panel focus-panel"><span className="focus-envelope" aria-hidden="true">✦</span><PanelHeading eyebrow={text('smartFlow', 'Yapay zeka')} title={text('balance', 'Bugünün dengesi')} /><div className="focus-score"><strong>72</strong><span>/ 100<br /><small>akış puanı</small></span></div><p className="focus-copy">Programın dengeli görünüyor. Randevuların arasında kendine alan bırakmışsın.</p><button className="primary-button" onClick={askFlow} disabled={thinking}>{thinking ? text('thinking', 'Düşünüyor…') : text('aiAsk', 'Yapay zeka önerisi al')} <Sparkles size={16} /></button>{suggestion && <p className="suggestion" role="status">{suggestion}</p>}</article></section>
    <section className="quick-actions-personal"><div><p className="eyebrow blue-label">{text('quickStart', 'HIZLI BAŞLANGIÇ')}</p><h2>{text('quickTitle', 'Akışına bir adım ekle.')}</h2></div><div className="quick-actions-personal-list">{quickActions.map(action => <Link to={action.to} key={action.label}><span>{action.icon}</span><b>{action.label}</b><small>{action.detail}</small><ArrowUpRight size={14} /></Link>)}</div></section>
    <section className="recommendation-band"><div><p className="eyebrow blue-label">ÖNCELİKLİ KONU</p><h2>Bugün sağlık ve bakım<br /><strong>öne çıkıyor.</strong></h2><p>İlk görüşmen yaklaşırken en işine yarayacak üç alan.</p></div><div className="recommendation-buttons"><Link to="/calendar" className="recommendation-button"><HeartPulse size={18} /><b>Sağlık randevuları</b><small>Görüşmelerini düzenle</small></Link><Link to="/stylesync" className="recommendation-button"><Scissors size={18} /><b>Bakım planı</b><small>Stil ve kuaför</small></Link><Link to="/intelligence" className="recommendation-button"><Sparkles size={18} /><b>Akıllı öneriler</b><small>Bugünü birlikte planla</small></Link></div></section>
    <section className="panel tasks-panel"><PanelHeading eyebrow="Yapılacaklar" title="Bugünün küçük adımları" action={<Link to="/space">Tümünü gör <ArrowUpRight size={14} /></Link>} /><div className="task-list">{taskList.map((task, i) => <button className={`task ${done.includes(i) ? 'is-done' : ''}`} key={task} onClick={() => setDone(v => v.includes(i) ? v.filter(x => x !== i) : [...v, i])}><span className="task-check">{done.includes(i) && <Check size={13} />}</span><span>{task}</span><small>{i === 0 ? 'Sağlık' : i === 1 ? 'İş' : 'Kişisel'}</small></button>)}</div></section>
  </>
}
function BusinessView({ suggestion, thinking, askFlow, labels }: { suggestion: string; thinking: boolean; askFlow: () => void; labels: Partial<Record<string, string | string[]>> }) { const text = (key: string, fallback: string) => String(labels[key] ?? fallback); return <><div className="business-view-head"><span>{text('businessWorkspace', 'Deniz Flow Studio için işletme çalışma alanı')}</span><Link to="/business" className="business-launch">{text('openBusiness', 'Tam işletme panelini aç')} <ArrowUpRight size={14} /></Link></div><section className="business-stats"><article className="stat-card"><CalendarDays /><span>{text('todayAppointments', 'Bugünkü randevular')}</span><strong>18</strong><small>+4 geçen haftaya göre</small></article><article className="stat-card"><Users /><span>Aktif danışanlar</span><strong>126</strong><small>12 yeni talep</small></article><article className="stat-card"><Settings2 /><span>Doluluk oranı</span><strong>%84</strong><small>Bu hafta · dengeli</small></article></section><section className="business-grid"><article className="panel schedule-panel"><PanelHeading eyebrow="İşletme takvimi" title="Bugünün akışı" action={<Link to="/calendar">Takvimi aç <ArrowUpRight size={14} /></Link>} /><div className="appointment-list">{[['09:00','Cilt bakımı','Ayşe Demir'],['10:30','Saç kesimi','Can Yıldız'],['13:00','İlk danışmanlık','Selin Akın'],['15:30','Renk uygulaması','Ece Kaya']].map(([time, title, person]) => <div className="appointment" key={time}><time>{time}</time><span className="event-line blue" /><div><strong>{title}</strong><p>{person}</p></div><span className="tag">Onaylı</span><ChevronRight size={16} className="chevron" /></div>)}</div><Link to="/book" className="add-row"><Plus size={15} /> Randevu oluştur</Link></article><article className="panel business-ai"><p className="eyebrow blue-label">Yapay zeka · işletme</p><h3>Yoğunluğunu<br />daha iyi yönet.</h3><p>Günün randevularını, ekip kapasitesini ve boşluklarını birlikte değerlendir.</p><button className="primary-button" onClick={askFlow} disabled={thinking}>{thinking ? 'Akış okunuyor…' : 'Akıllı özet al'} <Sparkles size={16} /></button>{suggestion && <p className="suggestion" role="status">{suggestion}</p>}</article></section><section className="business-tools"><Link to="/business"><CalendarDays /><b>Takvim ve uygunluk</b><small>İşletme panelinden yönet</small></Link><Link to="/business"><Settings2 /><b>Hizmet kategorileri</b><small>İşletme panelinden düzenle</small></Link><Link to="/business"><FileText /><b>İşletme notları</b><small>İşletme panelinden takip et</small></Link></section></> }
function NavItem({ icon, label, active, to }: { icon: React.ReactNode; label: string; active?: boolean; to?: '/' | '/calendar' | '/space' | '/tasks' | '/stylesync' | '/discover' | '/sports' | '/events' | '/intelligence' | '/notes' | '/personal-tools' }) { return to ? <Link to={to} className={`nav-item ${active ? 'active' : ''}`}>{icon}<span>{label}</span></Link> : <span className={`nav-item ${active ? 'active' : ''}`} aria-current={active ? 'page' : undefined}>{icon}<span>{label}</span></span> }
function PanelHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div>{action}</div> }
