import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowRight, Check, Clock3, Sparkles, Building2, ShieldCheck, UserRound } from 'lucide-react'
import { LanguageSelect, useI18n, type Lang } from '@/lib/i18n'

export const Route = createFileRoute('/pricing')({ head: () => ({ meta: [{ title: 'Planlar — Planmoy' }] }), component: Pricing })
type Plan = { name: string; price: string; description: string; features: string[]; icon: React.ReactNode; featured?: boolean }
type PricingCopy = { eyebrow:string; title:string; lead:string; trial:string; trialDetail:string; monthly:string; ai:string; aiDetail:string; choose:string; current:string; signIn:string; note:string; terms:string; popular:string; comparison:string }
const copy: Record<Lang, PricingCopy> = {
  tr:{eyebrow:'Sade ve ulaşılabilir planlar',title:'İşine ve akışına uygun planı seç.',lead:'Kişisel kullanımda güçlü bir başlangıç; işletmelerde hızlı ve net randevu yönetimi. Kart gerekmez.',trial:'İlk kurulum ücretsiz',trialDetail:'Hesap açınca 20 AI sorgusu dahil · ödeme yok',monthly:'aylık',ai:'AI sorgusu',aiDetail:'Her AI sorgusu planındaki kotadan düşer.',choose:'Bu planla başla',current:'Ücretsiz başla',signIn:'Zaten hesabın var mı? Giriş yap',note:'Ödeme veya checkout şu anda bağlı değil. Planmoy, randevu yönetimini benzer araçların altında konumlandırır; fiyatlar aktivasyon öncesi açıkça doğrulanır.',terms:'Kullanım koşulları ve gizlilik',popular:'En iyi başlangıç',comparison:'Kotalar ve farklar'},
  en:{eyebrow:'Simple, accessible plans',title:'Choose the plan for your work and flow.',lead:'A strong personal start, with fast and clear booking management for businesses. No card required.',trial:'Free first setup',trialDetail:'20 AI queries included when you create an account · no payment',monthly:'monthly',ai:'AI queries',aiDetail:'Every AI query uses your plan allowance.',choose:'Start with this plan',current:'Start free',signIn:'Already have an account? Sign in',note:'Payments and checkout are not connected yet. Planmoy is positioned below comparable scheduling tools; prices will be confirmed clearly before activation.',terms:'Terms and privacy',popular:'Best starting point',comparison:'Limits and differences'},
  de:{eyebrow:'Einfache, zugängliche Pläne',title:'Wähle den passenden Plan für deinen Ablauf.',lead:'Ein starker persönlicher Start und schnelle, klare Terminverwaltung für Unternehmen. Keine Karte nötig.',trial:'Kostenlose Ersteinrichtung',trialDetail:'20 KI-Anfragen bei der Kontoerstellung · keine Zahlung',monthly:'monatlich',ai:'KI-Anfragen',aiDetail:'Jede KI-Anfrage wird vom Planlimit abgezogen.',choose:'Mit diesem Plan starten',current:'Kostenlos starten',signIn:'Schon ein Konto? Anmelden',note:'Zahlungen und Checkout sind noch nicht verbunden. Planmoy liegt preislich unter vergleichbaren Tools; vor der Aktivierung werden die Preise klar bestätigt.',terms:'Bedingungen und Datenschutz',popular:'Bester Einstieg',comparison:'Limits und Unterschiede'},
  fr:{eyebrow:'Des offres simples et accessibles',title:'Choisissez l’offre adaptée à votre rythme.',lead:'Un démarrage personnel puissant et une gestion des rendez-vous rapide pour les entreprises. Sans carte.',trial:'Première configuration gratuite',trialDetail:'20 requêtes IA à la création du compte · sans paiement',monthly:'par mois',ai:'Requêtes IA',aiDetail:'Chaque requête IA utilise le quota de votre offre.',choose:'Commencer avec cette offre',current:'Commencer gratuitement',signIn:'Déjà un compte ? Se connecter',note:'Les paiements et le checkout ne sont pas encore connectés. Planmoy reste sous les tarifs des outils comparables ; les prix seront confirmés avant activation.',terms:'Conditions et confidentialité',popular:'Meilleur départ',comparison:'Limites et différences'},
  es:{eyebrow:'Planes sencillos y accesibles',title:'Elige el plan para tu trabajo y tu ritmo.',lead:'Un gran inicio personal y una gestión de citas rápida y clara para negocios. Sin tarjeta.',trial:'Configuración inicial gratis',trialDetail:'20 consultas de IA al crear la cuenta · sin pago',monthly:'al mes',ai:'Consultas de IA',aiDetail:'Cada consulta de IA consume tu cuota del plan.',choose:'Empezar con este plan',current:'Empezar gratis',signIn:'¿Ya tienes cuenta? Inicia sesión',note:'Los pagos y el checkout aún no están conectados. Planmoy se sitúa por debajo de herramientas comparables; los precios se confirmarán antes de activarlos.',terms:'Condiciones y privacidad',popular:'Mejor comienzo',comparison:'Límites y diferencias'},
  ar:{eyebrow:'خطط بسيطة ومتاحة',title:'اختر الخطة المناسبة لعملك ومسارك.',lead:'بداية قوية للاستخدام الشخصي وإدارة سريعة وواضحة للمواعيد للشركات. لا تحتاج إلى بطاقة.',trial:'الإعداد الأول مجاني',trialDetail:'20 استعلاماً للذكاء الاصطناعي عند إنشاء الحساب · دون دفع',monthly:'شهرياً',ai:'استعلامات الذكاء الاصطناعي',aiDetail:'يُخصم كل استعلام من حصة خطتك.',choose:'ابدأ بهذه الخطة',current:'ابدأ مجاناً',signIn:'لديك حساب؟ سجّل الدخول',note:'الدفع وCheckout غير متصلين حالياً. نضع Planmoy تحت أسعار الأدوات المشابهة؛ وستُؤكد الأسعار بوضوح قبل التفعيل.',terms:'الشروط والخصوصية',popular:'أفضل بداية',comparison:'الحدود والفروقات'},
  ru:{eyebrow:'Простые и доступные планы',title:'Выберите план для работы и своего потока.',lead:'Сильный старт для личного использования и быстрое управление встречами для бизнеса. Карта не нужна.',trial:'Бесплатная первичная настройка',trialDetail:'20 запросов ИИ при создании аккаунта · без оплаты',monthly:'в месяц',ai:'Запросы ИИ',aiDetail:'Каждый запрос ИИ списывается из лимита вашего плана.',choose:'Начать с этим планом',current:'Начать бесплатно',signIn:'Уже есть аккаунт? Войти',note:'Оплата и checkout пока не подключены. Planmoy находится ниже цен сопоставимых сервисов; перед активацией цены будут подтверждены.',terms:'Условия и конфиденциальность',popular:'Лучший старт',comparison:'Лимиты и различия'},
  zh:{eyebrow:'简单且易用的方案',title:'选择适合工作与日常流程的方案。',lead:'个人用户轻松开始，企业获得快速清晰的预约管理。无需银行卡。',trial:'首次设置免费',trialDetail:'创建账户即含 20 次 AI 查询 · 无需付款',monthly:'每月',ai:'AI 查询',aiDetail:'每次 AI 查询都会从方案额度中扣除。',choose:'选择此方案开始',current:'免费开始',signIn:'已有账户？登录',note:'付款和结账功能尚未连接。Planmoy 的定价低于同类工具；启用前会清楚确认价格。',terms:'条款与隐私',popular:'最佳起点',comparison:'额度与差异'},
}
const features: Record<Lang, { free:string[]; personal:string[]; solo:string[]; studio:string[] }> = {
  tr:{free:['Temel takvim ve randevu akışı','Kişisel veya işletme alanı','20 AI sorgusu · ilk kurulum'],personal:['Sınırsız kişisel randevu ve görev','Akıllı hatırlatıcılar ve hızlı destek','1.000 AI sorgusu / ay'],solo:['Tek kişi işletmesi için online rezervasyon','Müşteri notları ve otomatik hatırlatmalar','2.000 AI sorgusu / ay'],studio:['Ekip takvimi ve rol bazlı çalışma','Hizmet, müşteri ve yoğunluk görünümü','3.000 AI sorgusu / ay']},
  en:{free:['Core calendar and booking flow','Personal or business space','20 AI queries · first setup'],personal:['Unlimited personal appointments and tasks','Smart reminders and fast assistance','1,000 AI queries / month'],solo:['Online booking for one-person businesses','Client notes and automated reminders','2,000 AI queries / month'],studio:['Team calendar and role-based workspace','Services, clients and capacity view','3,000 AI queries / month']},
  de:{free:['Grundkalender und Terminablauf','Persönlicher oder geschäftlicher Bereich','20 KI-Anfragen · erste Einrichtung'],personal:['Unbegrenzte persönliche Termine und Aufgaben','Smarte Erinnerungen und schnelle Hilfe','1.000 KI-Anfragen / Monat'],solo:['Online-Buchung für Einzelunternehmen','Kundennotizen und automatische Erinnerungen','2.000 KI-Anfragen / Monat'],studio:['Teamkalender und rollenbasierter Bereich','Ansicht für Leistungen, Kunden und Auslastung','3.000 KI-Anfragen / Monat']},
  fr:{free:['Agenda et flux de réservation essentiels','Espace personnel ou entreprise','20 requêtes IA · première configuration'],personal:['Rendez-vous et tâches personnels illimités','Rappels intelligents et aide rapide','1 000 requêtes IA / mois'],solo:['Réservation en ligne pour indépendants','Notes clients et rappels automatiques','2 000 requêtes IA / mois'],studio:['Agenda d’équipe et rôles de travail','Vue services, clients et capacité','3 000 requêtes IA / mois']},
  es:{free:['Calendario y reservas básicos','Espacio personal o de negocio','20 consultas de IA · configuración inicial'],personal:['Citas y tareas personales ilimitadas','Recordatorios inteligentes y ayuda rápida','1.000 consultas de IA / mes'],solo:['Reservas online para profesionales independientes','Notas de clientes y recordatorios automáticos','2.000 consultas de IA / mes'],studio:['Calendario de equipo y roles','Vista de servicios, clientes y capacidad','3.000 consultas de IA / mes']},
  ar:{free:['التقويم الأساسي وتدفق الحجز','مساحة شخصية أو للأعمال','20 استعلام ذكاء اصطناعي · الإعداد الأول'],personal:['مواعيد ومهام شخصية غير محدودة','تذكيرات ذكية ومساعدة سريعة','1,000 استعلام ذكاء اصطناعي / شهر'],solo:['حجز إلكتروني للأعمال الفردية','ملاحظات العملاء وتذكيرات تلقائية','2,000 استعلام / شهر'],studio:['تقويم الفريق ومساحة حسب الأدوار','عرض الخدمات والعملاء والطاقة الاستيعابية','3,000 استعلام / شهر']},
  ru:{free:['Базовый календарь и поток записи','Личное или бизнес-пространство','20 запросов ИИ · первая настройка'],personal:['Неограниченные личные встречи и задачи','Умные напоминания и быстрая помощь','1 000 запросов ИИ / месяц'],solo:['Онлайн-запись для индивидуального бизнеса','Заметки клиентов и автоматические напоминания','2 000 запросов ИИ / месяц'],studio:['Календарь команды и роли','Обзор услуг, клиентов и загрузки','3 000 запросов ИИ / месяц']},
  zh:{free:['基础日历与预约流程','个人或企业空间','20 次 AI 查询 · 首次设置'],personal:['不限个人预约与任务','智能提醒与快速协助','每月 1,000 次 AI 查询'],solo:['适合个人经营者的在线预约','客户备注与自动提醒','每月 2,000 次 AI 查询'],studio:['团队日历与角色工作区','服务、客户与容量视图','每月 3,000 次 AI 查询']},
}
function Pricing() {
  const { lang } = useI18n(); const t = copy[lang]; const f = features[lang]
  const plans: Plan[] = [
    { name:'Free start', price:'$0', description:t.trialDetail, features:f.free, icon:<Clock3 size={20}/> },
    { name:'Personal', price:'$1.99', description:lang === 'tr' ? 'Kişisel planlama için hafif ve güçlü.' : 'Lightweight and powerful personal planning.', features:f.personal, icon:<UserRound size={20}/> },
    { name:'Solo', price:'$4.99', description:lang === 'tr' ? 'Tek kişilik hizmet işletmeleri için.' : 'For one-person service businesses.', features:f.solo, icon:<Sparkles size={20}/>, featured:true },
    { name:'Studio', price:'$12.99', description:lang === 'tr' ? 'Büyüyen ekipler için hızlı çalışma alanı.' : 'A fast workspace for growing teams.', features:f.studio, icon:<Building2 size={20}/> },
  ]
  return <main className="pricing-page"><header className="pricing-header"><Link to="/" className="auth-brand">plan<span>moy</span><i /></Link><div><LanguageSelect /><Link to="/auth" className="pricing-signin">{t.signIn}</Link></div></header><section className="pricing-hero"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.lead}</p><div className="trial-badge"><ShieldCheck size={16}/><strong>{t.trial}</strong><span>{t.trialDetail}</span></div></section><section className="pricing-grid">{plans.map(plan => <article key={plan.name} className={`pricing-card ${plan.featured ? 'featured' : ''}`}><div className="pricing-card-top"><span className="pricing-icon">{plan.icon}</span>{plan.featured && <span className="pricing-popular">{t.popular}</span>}</div><h2>{plan.name}</h2><p className="pricing-description">{plan.description}</p><div className="pricing-price"><strong>{plan.price}</strong><span>{t.monthly}</span></div><ul>{plan.features.map(feature => <li key={feature}><Check size={14}/>{feature}</li>)}</ul><Link to="/auth" search={{ plan: plan.name } as never} className="pricing-cta">{plan.name === 'Free start' ? t.current : t.choose}<ArrowRight size={15}/></Link></article>)}</section><section className="pricing-ai-note"><Sparkles size={18}/><div><strong>{t.ai}</strong><p>{t.aiDetail}</p></div></section><p className="pricing-note"><b>{t.comparison}:</b> {t.note} <Link to="/legal" hash="terms">{t.terms}</Link></p></main>
}
